### PR TITLE
Add Rust Kit

### PR DESCRIPTION
**Pull request by tye-singwa**
Hi! Added Rust kit support via both Docker & native cargo.
Also added documentation in both `README.md` and using doc comments. 
Included spec using generic executable, i think it should work, cause [Dimensions](https://github.com/StoneT2000/Dimensions) package doesnt support Rust yet.
Please tell me if anything is needed to finalize this PR.

### CODE REVIEW

**Comment by StoneT2000** [comment]
Thanks! And nice job with making this into an executable!

Ok given the number of new kits coming out suddenly (3 in a week!), i'll provide a test kaggle notebook where you can test your starter kit as ultimately the kit has to work on kaggle server vms (which are the same vms kaggle notebooks run on)

**Comment by tye-singwa** [comment]
Thanks for pointing in right direction. 
Will test on Windows VM & look through API inconsistencies.

**Comment by StoneT2000** [comment]
@tye-singwa Ok done! https://www.kaggle.com/stonet2000/lux-ai-2021-testing-new-non-python-starter-kits?scriptVersionId=76868015

Copy that and try running your rust agent using the notebook

**Comment by tye-singwa** [comment]
Hi, @StoneT2000!
Sorry for a delay, I've rewrote kit code to match API described in `README.md`. Also make it work on Kaggle notebook 
https://www.kaggle.com/valerich/lux-ai-2021-testing-rust-starter-kits.

**Comment by StoneT2000** [comment]
Thanks @tye-singwa for the contributions! Looks like everything is working, I'll merge this in and make an announcement to the community about this.

**Comment by tye-singwa** [comment]
Thanks @FranciscoGreco! Appreciate your help with Windows testing.

**Pull request merged**
